
import java.util.*;


//Q2 (a)
public class SurfaceAreaOFCyclinder {
public static void main(String[] args) {
    Random rand = new Random();

    int radius = rand.nextInt(10);
    int height = rand.nextInt(10);
        if(radius == 0) {
            radius+=1;
        }
        if(height == 0)
        {
            height+=1;
        }
    System.out.println("Radius Generated by Program : "+radius);
    System.out.println("Height Generated by Program : "+height);
    double area = (2*Math.PI*height*radius)+(2*Math.PI*(radius*radius));
        System.out.println("The Surface Area of Cylinder is : "+ String.format("%.3f", area));// String.format("%.3f", var) is used to set precision on decimal value
        double volume= Math.PI*Math.pow(radius,2)*height;
    System.out.println("The Volume of Cylinder is : "+ String.format("%.3f", volume));
    }


}
